"""Instance bootstrap payload generation.

hfvast does not yet ship its own OCI images (see runtime/ for the definitions
and the release workflow that will publish them). Until then, deployment uses
the pinned upstream backend image plus an INJECTED PAYLOAD:

  * the payload is one bash script (gateway + watchdog + downloader + backend
    launcher), gzipped, base64'd and split across ``HFVAST_PAYLOAD_nnn`` env
    vars;
  * a tiny ``onstart`` stub reassembles and runs it;
  * the backend binds to 127.0.0.1 only — the gateway (API-key authed) is the
    only public surface.

Secrets in the instance env: HF_TOKEN (user-supplied, fine-grained read-only
recommended), HFVAST_GATEWAY_KEY + HFVAST_BACKEND_KEY (deployment-scoped,
random). The unrestricted VAST_API_KEY is NEVER sent.
"""

from __future__ import annotations

import base64
import gzip
import shlex
from dataclasses import dataclass, field
from importlib import resources
from typing import Any

from hfvast import __version__
from hfvast.models.model import ModelFile

ROOT = "/opt/hfvast"
MODELS_DIR = f"{ROOT}/models"
GATEWAY_PORT = 8000
BACKEND_PORT = 8001

_ONSTART_STUB = """#!/bin/bash
# hfvast onstart stub — reassembles the payload from HFVAST_PAYLOAD_* env vars
mkdir -p {root}
: > {root}/payload.b64
i=0
while :; do
  var="HFVAST_PAYLOAD_$(printf '%03d' "$i")"
  val="${{!var:-}}"
  [ -z "$val" ] && break
  printf '%s' "$val" >> {root}/payload.b64
  i=$((i+1))
done
base64 -d {root}/payload.b64 | gunzip > {root}/payload.sh || {{ echo "hfvast: payload decode failed"; exit 1; }}
bash {root}/payload.sh 2>&1 | tee -a {root}/bootstrap.log
"""


@dataclass
class BootstrapSpec:
    deployment_id: str
    model_repo: str
    revision: str | None
    files: list[ModelFile]
    backend_cmd_args: list[str]
    gateway_key: str
    backend_key: str
    hf_token: str | None = None
    idle_timeout_s: float = 1800.0
    max_runtime_s: float = 6 * 3600.0
    gateway_port: int = GATEWAY_PORT
    backend_port: int = BACKEND_PORT
    extra_env: dict[str, str] = field(default_factory=dict)


def _resource_text(name: str) -> str:
    return resources.files("hfvast").joinpath(f"runtime/{name}").read_text(encoding="utf-8")


def build_onstart() -> str:
    return _ONSTART_STUB.format(root=ROOT)


def build_payload(spec: BootstrapSpec) -> str:
    """Generate the full bootstrap bash script."""
    gateway_src = _resource_text("gateway.py")
    watchdog_src = _resource_text("watchdog_container.py")

    files_tsv = "\n".join(f"{f.path}\t{f.size_bytes}" for f in spec.files) or ""
    base_url = f"https://huggingface.co/{spec.model_repo}/resolve/{spec.revision or 'main'}"
    backend_cmd = " ".join(arg.replace("@BACKEND_KEY@", spec.backend_key) for arg in spec.backend_cmd_args)

    script = f"""#!/bin/bash
# hfvast bootstrap payload — generated by hfvast {__version__}
# deployment: {spec.deployment_id}
set -uo pipefail
ROOT={shlex.quote(ROOT)}
MODELS_DIR={shlex.quote(MODELS_DIR)}
export HFVAST_STATE_FILE="$ROOT/state.json"
export HFVAST_ACTIVITY_FILE="$ROOT/last_activity"
export HFVAST_GATEWAY_PORT={spec.gateway_port}
export HFVAST_BACKEND_PORT={spec.backend_port}
export HFVAST_GATEWAY_KEY={shlex.quote(spec.gateway_key)}
export HFVAST_BACKEND_KEY={shlex.quote(spec.backend_key)}
export HFVAST_IDLE_TIMEOUT={spec.idle_timeout_s}
export HFVAST_MAX_RUNTIME={spec.max_runtime_s}
export HFVAST_GATEWAY_LOG="$ROOT/gateway.log"
mkdir -p "$ROOT" "$MODELS_DIR"

state() {{
  python3 - "$@" <<'PYSTATE'
import json, os, sys
p = os.environ.get("HFVAST_STATE_FILE", "/opt/hfvast/state.json")
try:
    s = json.load(open(p))
except Exception:
    s = {{"started_at": __import__("time").time()}}
key = sys.argv[1]
val = sys.argv[2] if len(sys.argv) > 2 else ""
s[key] = float(val) if val.replace(".", "", 1).isdigit() else val
json.dump(s, open(p, "w"))
PYSTATE
}}

state started_at "$(date +%s)"
state status provisioning
state message "checking dependencies"

if ! command -v python3 >/dev/null 2>&1 || ! command -v curl >/dev/null 2>&1; then
  (apt-get update -qq && apt-get install -y -qq --no-install-recommends \
   python3 curl ca-certificates) >>"$ROOT/bootstrap.log" 2>&1 || true
fi
if ! command -v python3 >/dev/null 2>&1; then
  state status error
  state message "python3 unavailable on this image and apt-get failed"
  exit 1
fi

cat > "$ROOT/gateway.py" <<'HFVAST_GATEWAY_EOF'
{gateway_src}
HFVAST_GATEWAY_EOF

cat > "$ROOT/watchdog.py" <<'HFVAST_WATCHDOG_EOF'
{watchdog_src}
HFVAST_WATCHDOG_EOF

umask 077
printf '%s' "$HFVAST_BACKEND_KEY" > "$ROOT/backend_api_key"
chmod 600 "$ROOT/backend_api_key" 2>/dev/null || true

nohup python3 "$ROOT/gateway.py" >>"$ROOT/gateway.log" 2>&1 &
echo $! > "$ROOT/gateway.pid"
nohup python3 "$ROOT/watchdog.py" >>"$ROOT/watchdog.log" 2>&1 &
echo $! > "$ROOT/watchdog.pid"

state status downloading
state message "downloading model"
cat > "$ROOT/files.tsv" <<'HFVAST_FILES_EOF'
{files_tsv}
HFVAST_FILES_EOF

BASE_URL={shlex.quote(base_url)}
TOTAL_BYTES=0
while IFS=$'\\t' read -r REL SIZE; do
  [ -z "$REL" ] && continue
  TOTAL_BYTES=$((TOTAL_BYTES + SIZE))
done < "$ROOT/files.tsv"
state bytes_total "$TOTAL_BYTES"

DONE_BYTES=0
while IFS=$'\\t' read -r REL SIZE; do
  [ -z "$REL" ] && continue
  NAME="$(basename "$REL")"
  DEST="$MODELS_DIR/$NAME"
  state message "downloading $NAME"
  AUTH=()
  if [ -n "${{HF_TOKEN:-}}" ]; then AUTH=(-H "Authorization: Bearer $HF_TOKEN"); fi
  try=0
  while :; do
    curl -fL --retry 5 --retry-delay 3 --connect-timeout 30 -C - \
      "${{AUTH[@]}}" -o "$DEST" "$BASE_URL/$REL"
    rc=$?
    if [ $rc -eq 0 ]; then break; fi
    try=$((try+1))
    if [ $try -ge 3 ]; then
      state status error
      state message "download failed for $NAME (curl rc=$rc after retries)"
      exit 1
    fi
    sleep 5
  done
  ACTUAL=$(stat -c%s "$DEST" 2>/dev/null || echo 0)
  if [ "$ACTUAL" -lt "$SIZE" ]; then
    state status error
    state message "downloaded size mismatch for $NAME ($ACTUAL < $SIZE)"
    exit 1
  fi
  DONE_BYTES=$((DONE_BYTES + SIZE))
  state bytes_done "$DONE_BYTES"
done < "$ROOT/files.tsv"

state status loading
state message "starting backend"
nohup bash -c {shlex.quote(backend_cmd)} >>"$ROOT/backend.log" 2>&1 &
echo $! > "$ROOT/backend.pid"

state message "waiting for backend health"
for i in $(seq 1 720); do
  CODE=$(curl -s -o /dev/null -w '%{{http_code}}' http://127.0.0.1:{spec.backend_port}/health || true)
  if [ "$CODE" = "200" ]; then
    state status ready
    state message "model ready"
    state ready_since "$(date +%s)"
    date +%s > "$ROOT/last_activity"
    exit 0
  fi
  if ! kill -0 "$(cat "$ROOT/backend.pid" 2>/dev/null)" 2>/dev/null; then
    state status error
    state message "backend process exited before becoming healthy — see backend.log"
    exit 1
  fi
  sleep 5
done
state status error
state message "backend did not become healthy in time"
exit 1
"""
    return script


def encode_payload(payload: str, chunk_size: int = 4096) -> dict[str, str]:
    """gzip → base64 → numbered env-var chunks."""
    compressed = base64.b64encode(gzip.compress(payload.encode("utf-8"), 9)).decode("ascii")
    chunks = [compressed[i : i + chunk_size] for i in range(0, len(compressed), chunk_size)]
    return {f"HFVAST_PAYLOAD_{i:03d}": chunk for i, chunk in enumerate(chunks)}


def decode_payload(env: dict[str, str]) -> str:
    """Inverse of encode_payload (used by tests and by the onstart stub logic)."""
    joined = "".join(value for key, value in sorted(env.items()) if key.startswith("HFVAST_PAYLOAD_"))
    return gzip.decompress(base64.b64decode(joined)).decode("utf-8")


def build_create_env(spec: BootstrapSpec, hf_token: str | None) -> dict[str, str]:
    """Full env dict for instance creation (secrets included — server-side only)."""
    env: dict[str, str] = {
        "-p 8000:8000": "1",
        "HFVAST_MODEL_LABEL": spec.deployment_id,
        "HFVAST_IDLE_TIMEOUT": str(spec.idle_timeout_s),
        "HFVAST_MAX_RUNTIME": str(spec.max_runtime_s),
        "HFVAST_GATEWAY_KEY": spec.gateway_key,
        "HFVAST_BACKEND_KEY": spec.backend_key,
    }
    if hf_token:
        env["HF_TOKEN"] = hf_token
    env.update(encode_payload(build_payload(spec)))
    env.update(spec.extra_env)
    return env


def describe_env(env: dict[str, str]) -> dict[str, Any]:
    """Safe description of creation env (no secret values) for logs/debug."""
    return {
        k: ("<set>" if k in {"HF_TOKEN", "HFVAST_GATEWAY_KEY", "HFVAST_BACKEND_KEY"} else v[:24])
        for k, v in sorted(env.items())
    }
